eureka :
  enviroment : PRD
  client :
    register-with-eureka : true
    fetch-registry : true
    serviceUrl :
      defaultZone : http://localhost:9002/eureka/
  server :
    enable-self-preservation : true