spring :
  cloud :
    config :
      server :
        git :
          uri : https://github.com/yuzhou586/spring-cloud-demo.git
          searchPaths : lemon-config
          username :
          password :
  